### ISSUE TITLE
minor problems

### ISSUE THREAD

**Issue by unique-usernames-are-annoying** [rrthomas/hpmor#176]
- [x] Chapter 7 line 650: Why was the original version of subtlety of a rampaging nundu changed to bull in a china shop? Even if one wants to replace the fictional nundu with an animal one does not have to google, i feel the rampaging part shouldn't be removed.
- [x] Chapter 12 line 55 Harry claps for Ron, but in line 69 it states now he'd only applauded Zabini. So either it should be changed to only having applauded Ron and Zabini or not having applauded Ron at all.
- [x] Chapter 23 line 138 or page 383 in the august release version there is one almost empty page due to the end{samepage}.
- [x] Chapter 25 line 33 it states that if magic had a big complex adaptation then this would never reassemble. Though as long as the odds are not 0 it could happen, so stating it would almost never happen, depending on how complex it is overall would be more accurate, although this can also be excused as Harry making a mistake.
- [x] Chapter 85 line 7 in the august release there is a larger empty space on page 1391 between put-up-or-shut-up,    stick-...

**Comment by rrthomas** [comment]
Thanks for these! It looks as though there should be more at the end of your issue; it seems to end mid-sentence?

**Comment by unique-usernames-are-annoying** [comment]
Nope, i only wanted to type the part of the line where that larger empty space was, so you can find it easily.

**Comment by rrthomas** [comment]
> Chapter 7 line 650: Why was the original version of subtlety of a rampaging nundu changed to bull in a china shop? Even if one wants to replace the fictional nundu with an animal one does not have to google, i feel the rampaging part shouldn't be removed.

I'll revert this. It's in a "Britfix" commit, so I guess I didn't realise it was a Harry Potter world creature.

**Comment by norwd** [comment]
> Chapter 12 line 55 Harry claps for Ron, but in line 69 it states now he'd only applauded Zabini. So either it should be changed to only having applauded Ron and Zabini or not having applauded Ron at all.

I've just checked [chapter 12](https://hpmor.com/chapter/12) in the original and it has the same inconsistency. Although given how close "Harry [...] started applauding" and "Harry applauded Zabini too" are to each-other, I'm not sure if this is a mistake by Yudkowsky or just ambiguous interpretation. Maybe clapping for your friends doesn't count? In any case, since that would be a deviation from the original source and not a correction in this repo I'm not sure if it needs fixing?

![image](https://github.com/user-attachments/assets/3e945696-4c5d-48f2-a542-79f9cb0d746e)
 
> Chapter 25 line 33 it states that if magic had a big complex adaptation then this would never reassemble. Though as long as the odds are not 0 it could happen, so stating it would almost never happen, depending on how complex it is overall would be more accurate, although this can also be excused as Harry making a mistake.

Same with this one, it's the same in the original (https://hpmor.com/chapter/25) as in this repo. That's not converting feet to meters, that's straight up changing the story, isn't it?

(Also on second thought, Harry is basically just rephrasing the laws of thermodynamics here, replace genes with air molecules and you get the standard explanation of why the air in a room never arranges all the slow molecules on the left hand side.)

**Comment by rrthomas** [comment]
@unique-usernames-are-annoying I agree with your suggestion that "Maybe clapping for your friends doesn't count?". I think the point is that Harry was starting to applaud Slytherins, but only managed one. I am happy to change that, I think I'd file it under the work an editor is supposed to do. I will make a small addition to suggest this.

Re chapter 25, agreed that this is not within the remit of an editor alone (the sort of query that one would raise with the author), so I will not do anything there.

**Comment by rrthomas** [comment]
I've done my best with the hyphenation/space issue; everything else is OK now, I believe. Closing.
