### ISSUE TITLE
reach out to Eliezer and ask him to update the links to the latest PDF and e-book files

### ISSUE THREAD

**Issue by entorb** [rrthomas/hpmor#33]
At
https://www.hpmor.com/
the links to the PDF, EPUB and MOBI versions should be updated to 
https://github.com/rjl20/hpmor/releases/latest/

Does anyone have a way of contacting Eliezer for asking him to perform this update?

Furthermore, since at https://www.hpmor.com/ there are download links for the 6 volumes, you might consider generating PDFs for those in the release-pipeline as well. For the e-book formats, I do not think this is necessary.

**Comment by rjl20** [comment]
Huh. I thought someone else had taken over the site a couple of years ago, but it looks like I'm still hosting it. I've gone ahead and linked to the latest release page rather than to the old individual PDFs, and removed the links to the old epub/mobi versions.

I think the reason for the existence of the 6-volume PDFs were so that people could print and bind their own physical book versions. I'm guessing anyone who was going to do that has done so by now.

**Comment by entorb** [comment]
Moin Josh, wow that was fast, thanks a lot!

Could you please also update the PDF and e-book links on this page:
http://www.hpmor.com/info/
?

And as you are already on it, please replace the link to the incomplete German translation by this complete one:
https://www.fanfiktion.de/s/60044849000ccc541aef297e/
and please also add links to my German e-book versions
https://entorb.net/hpmor/hpmor-de.epub
https://entorb.net/hpmor/hpmor-de.mobi

Generally, I very much like the split into the 6-volumes (and very much like their titles) and will file a new issue for PDF creation of these, as I am still considering printing them...

**Comment by rjl20** [comment]
Sure thing!

**Comment by rrthomas** [comment]
Thanks @rjl20 ! I didn't realise you had access to hpmor.com, or I'd've asked you to update the links ages ago (I tried to reach out to Eliezer directly and got nowhere).

I agree with @entorb that it's good to have links to the separate PDF volumes. If new readers are coming along, and reading the books, and would like physical editions, they will likely want the separate volumes, and there's no expiry date on that.

**Comment by rjl20** [comment]
Heh, I didn't either. I'll have to check my email to see what the last communication was, and from whom, because I could have sworn that I gave someone a copy of the site and they set it up on their own host three or four years ago. But it looks like the domain registration (which is not something I have access to) is still pointing to me, so my copy is still the active one. I hadn't thought to actually confirm that the process ever got completed, I guess.

**Comment by entorb** [comment]
Dear @rjl20, as I have just finished the conversion and merging of 4 German (part) translations into a [PDF LaTeX fork of this repo](https://github.com/entorb/hpmor-de), may I ask you to update the links on [hpmor.com](http://www.hpmor.com/info/) yet again?

* http://www.hpmor.com/info/ -> Translations -> German (complete) [latest release of PDF, epub, mobi](https://github.com/entorb/hpmor-de/releases/tag/WorkInProgress)

**Comment by entorb** [comment]
Thank you so much!

Do you know the meaning of bold font regarding the translations on that page? I see the first few are in bold, while the rest are in normal font.

**Comment by rjl20** [comment]
Can do. Should this replace the following line?


   - German <https://www.fanfiktion.de/s/60044849000ccc541aef297e/> by
   Schneefl0cke (complete, also EPUB
   <https://entorb.net/hpmor/hpmor-de.epub> and MOBI
   <https://entorb.net/hpmor/hpmor-de.mobi>)

--Josh

**Comment by entorb** [comment]
yes please
