### ISSUE TITLE
Shall we use GitHub actions to automatically compile a new pdf and ebook upon every commit to master?

### ISSUE THREAD

**Issue by entorb** [rrthomas/hpmor#56]
What to you think about using GitHub actions to automatically compile a new PDF and e-book upon every commit to master?

Here an example for a [config file](https://github.com/entorb/COVID-19-Coronavirus-German-Regions/blob/master/.github/workflows/de.yml) from anther project of mine.

We would need to set the trigger to 
`
on:
  push: 
    branches: [ master ]
`

install the latex packages via 
`
sudo apt install [packages] > /dev/null
`

And define a static tag/version to publish to, for example "daily".

**Comment by rrthomas** [comment]
If you'd like to make a PR for that, that would be great. What would be most interesting (and save me time, at least!) would be if that was also done for releases, so that merely tagging a release would be enough to make it. I guess that would need some extra work, but again I imagine there must be existing models to copy.

**Comment by entorb** [comment]
working, results can be found at: https://github.com/rrthomas/hpmor/releases/tag/WorkInProgress
