### ISSUE TITLE
dash harmonization

### ISSUE THREAD

**Issue by entorb** [rrthomas/hpmor#73]
in https://github.com/rrthomas/hpmor/blob/0ef048437b978a25665316f2bbde52d4d5172a3c/chapters/hpmor-chapter-008.tex#L201
we find "2-4-6" using "minus" as dash.

in https://github.com/rrthomas/hpmor/blob/0ef048437b978a25665316f2bbde52d4d5172a3c/chapters/hpmor-chapter-008.tex#L213 
we find "4–6–8" using a "mid-length" dash

in most other cases the "—" "em dash" is used.

What is the rule of when to apply the "mid-length" dash? Is it also used between words, or only between numbers? Would be nice to harmonize it.

**Comment by rrthomas** [comment]
For numbers it's fairly simple: ranges use en dashes (mid-length). So, 2-4-6 should be fixed to 2–4–6.

For words, there's no rule just based on the characters: normally one uses a hyphen ("high-security"), but for a compound where the parts are equal, an en dash ("black–crimson fire"), or where a compound is being joined to a modifier with a hyphen ("grown-up–sized", where you would otherwise have "child-sized").

**Comment by entorb** [comment]
Thank you! So I coded only a role for the numbers and did only find the ones above.
